services:
  - type: web
    name: restaurant-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn backend.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:///backend/database/restaurant.db
      - key: ALLOWED_ORIGINS
        value: "https://restaurant-management-system.vercel.app,https://restaurant-management-system-*.vercel.app,http://localhost:5173,http://localhost:3000"
      - key: JWT_SECRET_KEY
        value: "TRYXQMbll9xoTZohCfcf2UGuF62cr5xVTN+ADmb8SXY="
      - key: ENVIRONMENT
        value: "production"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ALLOW_METHODS
        value: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
      - key: CORS_ALLOW_HEADERS
        value: "Content-Type,Authorization,Accept,Origin,X-Requested-With,X-CSRF-Token,Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers"
      - key: CORS_EXPOSE_HEADERS
        value: "*"
      - key: CORS_MAX_AGE
        value: "3600"
      - key: MAX_UPLOAD_SIZE
        value: "10485760"  # 10MB in bytes
      - key: CORS_ALLOW_ORIGIN_REGEX
        value: "https://restaurant-management-system.*\\.vercel\\.app"
    disk:
      name: data
      mountPath: /opt/render/project/src/static
      sizeGB: 1
    healthCheckPath: /health
    healthCheckInterval: 60s
    autoDeploy: true 