services:
  - type: web
    name: restaurant-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn backend.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:///backend/database/restaurant.db
      - key: ALLOWED_ORIGINS
        value: "https://restaurant-management-system-e0fkd5c01-vinesh-vonterus-projects.vercel.app,http://localhost:5173,http://localhost:3000"
      - key: JWT_SECRET_KEY
        value: "TRYXQMbll9xoTZohCfcf2UGuF62cr5xVTN+ADmb8SXY="
      - key: ENVIRONMENT
        value: "production"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ALLOW_METHODS
        value: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
      - key: CORS_ALLOW_HEADERS
        value: "*"
      - key: CORS_EXPOSE_HEADERS
        value: "*"
      - key: CORS_MAX_AGE
        value: "3600"
    healthCheckPath: /health
    healthCheckInterval: 60s
    autoDeploy: true 